
export const GET_PIZZA_SIZES_ATTEMPT = "GET_PIZZA_SIZES_ATTEMPT"
export const GET_PIZZA_SIZES_SUCCESS = "GET_PIZZA_SIZES_SUCCESS"
export const GET_PIZZA_SIZES_FAILURE = "GET_PIZZA_SIZES_FAILURE"
export const ADD_NEW_PIZZA = "ADD_NEW_PIZZA"
